language: "perl"

services:
  - mysql

os: linux
dist: xenial

perl:
  - "5.26"
  - "5.14"

env:
  - COVERALLS=true  DB=mysql
  
addons:
  apt:
    packages:
    - unzip

install:
    - cpanm -n -q Devel::Cover::Report::Coveralls DBD::SQLite JSON Proc::Daemon
    - cp travisci/MultiTestDB.conf.travisci.mysql  modules/t/MultiTestDB.conf.mysql
    - cp travisci/MultiTestDB.conf.travisci.SQLite modules/t/MultiTestDB.conf.SQLite
    - cpanm -n -q --installdeps --cpanfile=ensembl/cpanfile .

script: "./travisci/harness.sh"

# Get the matrix to only build coveralls support when on 5.10
jobs:
  exclude:
    - perl: "5.14"
      env: COVERALLS=false DB=mysql
    - perl: "5.14"
      env: COVERALLS=false DB=sqlite
    - perl: "5.14"
      env: COVERALLS=true  DB=mysql

notifications:
  email:
    on_success: always
    on_failure: always
